import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from "fs";
import { dirname, extname, join, resolve } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const root = resolve(__dirname, "..");
const iconsDir = join(root, "icons");
const distDir = join(root, "dist");
const reactDir = join(distDir, "react");
const reactIconsDir = join(reactDir, "icons");
const vueDir = join(distDir, "vue");
const vueIconsDir = join(vueDir, "icons");

const supportedVariants = ["mark", "standard"] as const;
const supportedAppearances = ["default", "monochrome"] as const;

type BrandFile = {
  key: string;
  name: string;
  variant: string;
  appearance: string;
  fullPath: string;
  sourceRel: string;
  componentName: string;
  isAlmaVariant: boolean;
};

function ensureDir(dir: string) {
  mkdirSync(dir, { recursive: true });
}

function cleanDir(dir: string) {
  if (existsSync(dir)) rmSync(dir, { recursive: true, force: true });
  ensureDir(dir);
}

function walk(dir: string): string[] {
  return readdirSync(dir)
    .sort((a, b) => a.localeCompare(b))
    .flatMap((entry) => {
      const fullPath = join(dir, entry);
      const stats = statSync(fullPath);

      if (stats.isDirectory()) return walk(fullPath);
      if (stats.isFile() && extname(entry) === ".svg") return [fullPath];

      return [];
    });
}

function parseFileName(filePath: string) {
  const base = filePath.split(/[\\/]/).pop()!;
  const key = base.replace(/\.svg$/, "");
  const parts = key.split("_");

  if (parts.length !== 3) {
    throw new Error(`Unexpected brand asset name format: ${base}`);
  }

  const [name, variant, appearance] = parts;

  return {
    key,
    name,
    variant,
    appearance,
  };
}

function toPascalCase(value: string) {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .split(/[^A-Za-z0-9]+|\s+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function toComponentName({
  name,
  variant,
  appearance,
}: Pick<BrandFile, "name" | "variant" | "appearance">) {
  const componentName = `${toPascalCase(name)}${toPascalCase(
    variant,
  )}${toPascalCase(appearance)}`;

  return /^[A-Za-z]/.test(componentName)
    ? componentName
    : `Brand${componentName}`;
}

function quote(value: string) {
  return JSON.stringify(value);
}

function union(values: string[]) {
  if (!values.length) return "never";
  return values.map((value) => `  | ${quote(value)}`).join("\n");
}

function writeGenerated(filePath: string, content: string) {
  ensureDir(dirname(filePath));
  writeFileSync(filePath, `${content.trimEnd()}\n`, "utf8");
}

function extractSvg(svg: string, filePath: string) {
  const match = svg.match(/<svg\b([^>]*)>([\s\S]*?)<\/svg>\s*$/i);

  if (!match) throw new Error(`Unable to parse SVG: ${filePath}`);

  const attrs = Object.fromEntries(
    [...match[1].matchAll(/([:\w-]+)\s*=\s*"([^"]*)"/g)].map((attr) => [
      attr[1],
      attr[2],
    ]),
  );

  return {
    viewBox: attrs.viewBox ?? "0 0 24 24",
    xmlns: attrs.xmlns ?? "http://www.w3.org/2000/svg",
    inner: match[2].trim(),
  };
}

function renderComponentManifest(entries: BrandFile[]) {
  return entries
    .map(
      ({ key, componentName }) =>
        `  ${quote(key)}: () => import(${quote(`./icons/${componentName}.js`)})`,
    )
    .join(",\n");
}

function renderMetadataDts(entries: BrandFile[]) {
  const names = [...new Set(entries.map(({ name }) => name))].sort((a, b) =>
    a.localeCompare(b),
  );

  const variants = [...new Set(entries.map(({ variant }) => variant))].sort(
    (a, b) => a.localeCompare(b),
  );

  const appearances = [
    ...new Set(entries.map(({ appearance }) => appearance)),
  ].sort((a, b) => a.localeCompare(b));

  return `// AUTO-GENERATED by AlmaBrandsResolver

export type AlmaBrandName =
${union(names)};

export type AlmaBrandVariant =
${union(variants)};

export type AlmaBrandAppearance =
${union(appearances)};

export type AlmaBrandFullName = \`\${AlmaBrandName}_\${AlmaBrandVariant}_\${AlmaBrandAppearance}\`;

export type BrandName = AlmaBrandName;
export type BrandVariant = AlmaBrandVariant;
export type BrandAppearance = AlmaBrandAppearance;
export type BrandFullName = AlmaBrandFullName;

export declare const brandNames: readonly AlmaBrandName[];
export declare const brandVariants: readonly AlmaBrandVariant[];
export declare const brandAppearances: readonly AlmaBrandAppearance[];
export declare const brandFullNames: readonly AlmaBrandFullName[];

export type AlmaBrandResolveInput = {
  name: AlmaBrandName;
  variant?: AlmaBrandVariant;
  appearance?: AlmaBrandAppearance;
};

export declare function resolveBrandKey(input: AlmaBrandResolveInput): AlmaBrandFullName;

export declare function hasBrandVariant(input: AlmaBrandResolveInput): boolean;

export declare const brandManifest: Record<AlmaBrandFullName, () => Promise<unknown>>;
`;
}

function renderMetadataJs(entries: BrandFile[]) {
  const names = [...new Set(entries.map(({ name }) => name))].sort((a, b) =>
    a.localeCompare(b),
  );

  const variants = [...new Set(entries.map(({ variant }) => variant))].sort(
    (a, b) => a.localeCompare(b),
  );

  const appearances = [
    ...new Set(entries.map(({ appearance }) => appearance)),
  ].sort((a, b) => a.localeCompare(b));

  const fullNames = entries
    .map(({ key }) => key)
    .sort((a, b) => a.localeCompare(b));

  return `// AUTO-GENERATED by AlmaBrandsResolver

export const brandNames = ${JSON.stringify(names, null, 2)};

export const brandVariants = ${JSON.stringify(variants, null, 2)};

export const brandAppearances = ${JSON.stringify(appearances, null, 2)};

export const brandFullNames = ${JSON.stringify(fullNames, null, 2)};

export const brandManifest = {
${renderComponentManifest(entries)}
};

export function resolveBrandKey({
  name,
  variant = "mark",
  appearance = "default",
}) {
  return \`\${name}_\${variant}_\${appearance}\`;
}

export function hasBrandVariant(input) {
  return Object.prototype.hasOwnProperty.call(brandManifest, resolveBrandKey(input));
}
`;
}

function renderReactComponent(entry: BrandFile) {
  const svg = extractSvg(readFileSync(entry.fullPath, "utf8"), entry.fullPath);

  return `import * as React from "react";

export default function ${entry.componentName}({
  size = 24,
  decorative = true,
  ...props
}) {
  const ariaHidden = decorative ? true : undefined;
  const role = decorative ? undefined : "img";

  return React.createElement(
    "svg",
    {
      width: size,
      height: size,
      viewBox: ${quote(svg.viewBox)},
      xmlns: ${quote(svg.xmlns)},
      "aria-hidden": ariaHidden,
      role,
      ...props,
    },
    React.createElement("g", {
      dangerouslySetInnerHTML: { __html: ${quote(svg.inner)} },
    }),
  );
}
`;
}

function renderReactComponentDts(entry: BrandFile) {
  return `import type * as React from "react";

export type ${entry.componentName}Props = React.SVGProps<SVGSVGElement> & {
  size?: number | string;
  decorative?: boolean;
};

export default function ${entry.componentName}(props: ${entry.componentName}Props): React.ReactElement;
`;
}

function renderVueComponent(entry: BrandFile) {
  const svg = extractSvg(readFileSync(entry.fullPath, "utf8"), entry.fullPath);

  return `import { defineComponent, h } from "vue";

export default defineComponent({
  name: ${quote(entry.componentName)},
  props: {
    size: { type: [Number, String], default: 24 },
    decorative: { type: Boolean, default: true },
  },
  setup(props, { attrs }) {
    return () =>
      h(
        "svg",
        {
          ...attrs,
          width: props.size,
          height: props.size,
          viewBox: ${quote(svg.viewBox)},
          xmlns: ${quote(svg.xmlns)},
          "aria-hidden": props.decorative ? true : undefined,
          role: props.decorative ? undefined : "img",
        },
        [
          h("g", { innerHTML: ${quote(svg.inner)} }),
        ],
      );
  },
});
`;
}

function renderVueComponentDts(entry: BrandFile) {
  return `import type { DefineComponent } from "vue";

export type ${entry.componentName}Props = {
  size?: number | string;
  decorative?: boolean;
};

declare const ${entry.componentName}: DefineComponent<${entry.componentName}Props>;

export default ${entry.componentName};
`;
}

function renderReactIndex(entries: BrandFile[]) {
  return entries
    .map(
      ({ componentName }) =>
        `export { default as ${componentName} } from "./${componentName}.js";`,
    )
    .join("\n");
}

function renderVueIndex(entries: BrandFile[]) {
  return renderReactIndex(entries);
}

function renderDynamicReactDts() {
  return `import type * as React from "react";
import type { AlmaBrandName, AlmaBrandVariant, AlmaBrandAppearance } from "../metadata.js";

export type AlmaBrandProps = React.SVGProps<SVGSVGElement> & {
  name: AlmaBrandName;
  variant?: AlmaBrandVariant;
  appearance?: AlmaBrandAppearance;
  size?: number | string;
  decorative?: boolean;
};

export declare function AlmaBrand(props: AlmaBrandProps): React.ReactElement | null;
`;
}

function renderDynamicVueDts() {
  return `import type { DefineComponent } from "vue";
import type { AlmaBrandName, AlmaBrandVariant, AlmaBrandAppearance } from "../metadata.js";

export type AlmaBrandProps = {
  name: AlmaBrandName;
  variant?: AlmaBrandVariant;
  appearance?: AlmaBrandAppearance;
  size?: number | string;
  decorative?: boolean;
};

export declare const AlmaBrand: DefineComponent<AlmaBrandProps>;
`;
}

function renderDynamicReactJs() {
  return `import * as React from "react";
import { brandManifest, resolveBrandKey } from "../metadata.js";

export function AlmaBrand({
  name,
  variant = "mark",
  appearance = "default",
  ...props
}) {
  const key = resolveBrandKey({ name, variant, appearance });
  const loader = brandManifest[key];

  const LazyBrand = React.useMemo(() => {
    return loader ? React.lazy(loader) : null;
  }, [loader]);

  if (!LazyBrand) return null;

  return React.createElement(
    React.Suspense,
    { fallback: null },
    React.createElement(LazyBrand, props),
  );
}
`;
}

function renderDynamicVueJs() {
  return `import { defineAsyncComponent, defineComponent, h } from "vue";
import { brandManifest, resolveBrandKey } from "../metadata.js";

export const AlmaBrand = defineComponent({
  name: "AlmaBrand",
  props: {
    name: { type: String, required: true },
    variant: { type: String, default: "mark" },
    appearance: { type: String, default: "default" },
    size: { type: [Number, String], default: 24 },
    decorative: { type: Boolean, default: true },
  },
  setup(props, { attrs }) {
    return () => {
      const key = resolveBrandKey({
        name: props.name,
        variant: props.variant,
        appearance: props.appearance,
      });

      const loader = brandManifest[key];
      if (!loader) return null;

      const Component = defineAsyncComponent(loader);

      return h(Component, {
        ...attrs,
        size: props.size,
        decorative: props.decorative,
      });
    };
  },
});
`;
}

const files = walk(iconsDir);

const entries = files
  .map((fullPath): BrandFile => {
    const parsed = parseFileName(fullPath);

    return {
      ...parsed,
      fullPath,
      sourceRel: `./icons/${parsed.key}.svg`,
      componentName: toComponentName(parsed),
      isAlmaVariant:
        (supportedVariants as readonly string[]).includes(parsed.variant) &&
        (supportedAppearances as readonly string[]).includes(parsed.appearance),
    };
  })
  .filter((entry) => entry.isAlmaVariant)
  .sort((a, b) => a.key.localeCompare(b.key));

cleanDir(distDir);
ensureDir(reactIconsDir);
ensureDir(vueIconsDir);

for (const entry of entries) {
  writeGenerated(
    join(reactIconsDir, `${entry.componentName}.js`),
    renderReactComponent(entry),
  );
  writeGenerated(
    join(reactIconsDir, `${entry.componentName}.d.ts`),
    renderReactComponentDts(entry),
  );

  writeGenerated(
    join(vueIconsDir, `${entry.componentName}.js`),
    renderVueComponent(entry),
  );
  writeGenerated(
    join(vueIconsDir, `${entry.componentName}.d.ts`),
    renderVueComponentDts(entry),
  );
}

writeGenerated(join(reactIconsDir, "index.js"), renderReactIndex(entries));
writeGenerated(join(reactIconsDir, "index.d.ts"), renderReactIndex(entries));

writeGenerated(join(vueIconsDir, "index.js"), renderVueIndex(entries));
writeGenerated(join(vueIconsDir, "index.d.ts"), renderVueIndex(entries));

writeGenerated(join(reactDir, "index.js"), renderDynamicReactJs());
writeGenerated(join(reactDir, "index.d.ts"), renderDynamicReactDts());

writeGenerated(join(vueDir, "index.js"), renderDynamicVueJs());
writeGenerated(join(vueDir, "index.d.ts"), renderDynamicVueDts());

writeGenerated(join(distDir, "metadata.js"), renderMetadataJs(entries));
writeGenerated(join(distDir, "metadata.d.ts"), renderMetadataDts(entries));

writeGenerated(
  join(distDir, "manifest.js"),
  `export { brandManifest } from "./metadata.js";`,
);

writeGenerated(
  join(distDir, "manifest.d.ts"),
  `export { brandManifest } from "./metadata.js";`,
);

writeGenerated(join(distDir, "index.js"), `export * from "./metadata.js";`);

writeGenerated(join(distDir, "index.d.ts"), `export * from "./metadata.js";`);

console.log(
  `Generated Alma Brands package surface: ${entries.length} brand assets.`,
);
